import { Injectable } from '@nestjs/common';
import { BaseAgent, AgentOutput } from './base-agent';

@Injectable()
export class InvestmentAnalystAgent extends BaseAgent {
  readonly id = 'agent.investment_analyst';
  readonly name = 'Investment Analyst';
  readonly description = 'Fundamental analysis, valuation, business model assessment';

  private readonly systemPrompt = `You are a senior equity research analyst. Analyze companies using rigorous fundamental analysis. Always cite specific financial metrics, compare to industry peers, and assess competitive moats. Present bull/base/bear cases with probability estimates. Never make buy/sell recommendations — present analysis for the user to make their own informed decision.

Output format:
- Executive summary (2-3 sentences)
- Key metrics and how they compare to peers
- Growth drivers and risks
- Valuation assessment (overvalued/fairly valued/undervalued relative to peers and history)
- Bull/Base/Bear scenarios with probability estimates`;

  async execute(query: string, context: any): Promise<AgentOutput> {
    // In production: calls OpenAI/Anthropic with context-enriched prompt
    // This is the integration point for the LLM provider

    const symbols = context.symbols ?? [];
    const fundamentals = context.fundamentals ?? {};

    // TODO: Replace with actual LLM call
    const content = this.generatePlaceholderAnalysis(query, symbols, fundamentals);

    return {
      agentId: this.id,
      content,
      confidence: 75,
      sources: [
        { type: 'financial_data', reference: 'Latest quarterly filings', freshness: new Date().toISOString() },
        { type: 'market_data', reference: 'Real-time market data', freshness: new Date().toISOString() },
      ],
      tokensUsed: 500,
    };
  }

  private generatePlaceholderAnalysis(query: string, symbols: string[], fundamentals: any): string {
    if (symbols.length === 0) {
      return 'Please specify a stock symbol for me to analyze.';
    }
    const symbol = symbols[0];
    return `## ${symbol} — Fundamental Analysis\n\n` +
      `Based on the latest available financial data, here is my assessment of ${symbol}:\n\n` +
      `**Business Model:** [Analysis would be generated by LLM with real data]\n\n` +
      `**Key Metrics vs Peers:** P/E, Revenue Growth, ROE comparisons\n\n` +
      `**Moat Assessment:** [Evaluation of competitive advantages]\n\n` +
      `**Scenarios:**\n` +
      `- Bull (30%): [Upside case]\n` +
      `- Base (50%): [Most likely outcome]\n` +
      `- Bear (20%): [Downside risk]\n`;
  }
}
