'use client';

import { useState } from 'react';
import {
  FileDown, Loader2, Shield, TrendingUp, Brain, Target,
  ClipboardCheck, AlertTriangle, CheckCircle2, User,
} from 'lucide-react';


export default function ReportPage() {
  const [generating, setGenerating] = useState(false);
  const [report, setReport] = useState<Report | null>(null);

  function generateReport() {
    setGenerating(true);
    // All data is from localStorage — no backend needed
    setTimeout(() => {
      const data = buildReport();
      setReport(data);
      setGenerating(false);
    }, 1500);
  }

  function exportPDF() {
    if (!report) return;
    // Use browser print as PDF export
    const printContent = document.getElementById('report-content');
    if (!printContent) return;
    const win = window.open('', '_blank');
    if (!win) return;
    win.document.write(`
      <html><head><title>SmartVest Investor Profile Report</title>
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, sans-serif; padding: 40px; color: #1a1a1a; font-size: 12px; line-height: 1.6; }
        h1 { font-size: 22px; margin-bottom: 4px; }
        h2 { font-size: 16px; margin-top: 28px; border-bottom: 1px solid #ddd; padding-bottom: 4px; }
        h3 { font-size: 13px; margin-top: 16px; }
        .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }
        .card { border: 1px solid #ddd; padding: 12px; border-radius: 6px; }
        .green { color: #16a34a; } .red { color: #dc2626; } .yellow { color: #ca8a04; }
        .muted { color: #6b7280; font-size: 11px; }
        table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        td, th { border: 1px solid #ddd; padding: 6px 8px; text-align: left; font-size: 11px; }
        th { background: #f9fafb; }
        .summary { background: #f0f9ff; padding: 16px; border-radius: 8px; margin-top: 20px; }
        @media print { body { padding: 20px; } }
      </style></head><body>
      ${printContent.innerHTML}
      <p class="muted" style="margin-top:40px;text-align:center">Generated by SmartVest · ${new Date().toLocaleDateString()} · Not financial advice</p>
      </body></html>
    `);
    win.document.close();
    setTimeout(() => win.print(), 500);
  }

  return (
    <div className="max-w-4xl space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-indigo-500/10">
            <FileDown className="h-5 w-5 text-indigo-400" />
          </div>
          <div>
            <h1 className="text-xl font-bold">Investor Profile Report</h1>
            <p className="text-xs text-[var(--muted)]">
              Complete PDF export for yourself or a financial advisor
            </p>
          </div>
        </div>
        {report && (
          <button onClick={exportPDF} className="rounded-lg bg-indigo-500 px-4 py-2 text-xs font-semibold text-white hover:bg-indigo-600 flex items-center gap-2">
            <FileDown className="h-3.5 w-3.5" />Export PDF
          </button>
        )}
      </div>

      {/* Generate Button */}
      {!report && (
        <div className="rounded-xl border border-[var(--card-border)] bg-[var(--card)] p-8 text-center space-y-4">
          <ClipboardCheck className="h-12 w-12 text-[var(--muted)]/30 mx-auto" />
          <div>
            <p className="text-sm font-semibold">Generate Your Complete Report</p>
            <p className="text-xs text-[var(--muted)] mt-1 max-w-md mx-auto">
              Pulls all your data: risk profile, portfolio, performance, behavioral analysis,
              thesis track record, and generates a one-page investor summary.
            </p>
          </div>
          <button onClick={generateReport} disabled={generating}
            className="rounded-xl bg-indigo-500 px-8 py-3.5 text-sm font-semibold text-white hover:bg-indigo-600 disabled:opacity-50 flex items-center gap-2 mx-auto">
            {generating ? <Loader2 className="h-4 w-4 animate-spin" /> : <FileDown className="h-4 w-4" />}
            {generating ? 'Generating...' : 'Generate Report'}
          </button>
        </div>
      )}


      {/* Report Content */}
      {report && (
        <div id="report-content" className="space-y-6">
          {/* Section 1: Risk Profile */}
          <div className="rounded-xl border border-[var(--card-border)] bg-[var(--card)] p-5 space-y-3">
            <div className="flex items-center gap-2">
              <Shield className="h-4 w-4 text-indigo-400" />
              <h2 className="text-sm font-bold">Risk Profile</h2>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <p className="text-[10px] text-[var(--muted)]">Profile</p>
                <p className="text-lg font-bold">{report.riskProfile}</p>
              </div>
              <div>
                <p className="text-[10px] text-[var(--muted)]">Investor Since</p>
                <p className="text-sm font-medium">{report.startDate || 'Unknown'}</p>
              </div>
            </div>
          </div>

          {/* Section 2: Portfolio */}
          <div className="rounded-xl border border-[var(--card-border)] bg-[var(--card)] p-5 space-y-3">
            <div className="flex items-center gap-2">
              <TrendingUp className="h-4 w-4 text-indigo-400" />
              <h2 className="text-sm font-bold">Portfolio ({report.holdings.length} holdings)</h2>
            </div>
            <div className="grid grid-cols-3 gap-3">
              <div className="rounded-lg bg-[var(--background)] p-3 text-center">
                <p className="text-[9px] text-[var(--muted)]">Total Value (USD)</p>
                <p className="text-sm font-bold font-tabular">${report.totalUSD.toLocaleString('en-US', {maximumFractionDigits:0})}</p>
              </div>
              <div className="rounded-lg bg-[var(--background)] p-3 text-center">
                <p className="text-[9px] text-[var(--muted)]">Total Value (DKK)</p>
                <p className="text-sm font-bold font-tabular">{report.totalDKK.toLocaleString('da-DK', {maximumFractionDigits:0})} kr</p>
              </div>
              <div className="rounded-lg bg-[var(--background)] p-3 text-center">
                <p className="text-[9px] text-[var(--muted)]">Total Return</p>
                <p className={`text-sm font-bold font-tabular ${report.totalReturnPct >= 0 ? 'text-[var(--gain)]' : 'text-[var(--loss)]'}`}>
                  {report.totalReturnPct >= 0 ? '+' : ''}{report.totalReturnPct.toFixed(1)}%
                </p>
              </div>
            </div>
            {report.holdings.length > 0 && (
              <div className="overflow-x-auto">
                <table className="w-full text-[10px]">
                  <thead><tr className="text-[var(--muted)] border-b border-[var(--card-border)]">
                    <th className="text-left py-1.5">Symbol</th><th className="text-right py-1.5">Shares</th>
                    <th className="text-right py-1.5">Avg Cost</th><th className="text-right py-1.5">Value</th>
                  </tr></thead>
                  <tbody>{report.holdings.slice(0, 15).map(h => (
                    <tr key={h.symbol} className="border-b border-[var(--card-border)]/30">
                      <td className="py-1 font-medium">{h.symbol}</td>
                      <td className="py-1 text-right font-tabular">{h.shares}</td>
                      <td className="py-1 text-right font-tabular">${h.avgCost.toFixed(2)}</td>
                      <td className="py-1 text-right font-tabular">${(h.shares * h.avgCost).toLocaleString('en-US', {maximumFractionDigits:0})}</td>
                    </tr>
                  ))}</tbody>
                </table>
              </div>
            )}
          </div>

          {/* Section 3: Thesis Track Record */}
          <div className="rounded-xl border border-[var(--card-border)] bg-[var(--card)] p-5 space-y-3">
            <div className="flex items-center gap-2">
              <Target className="h-4 w-4 text-indigo-400" />
              <h2 className="text-sm font-bold">Investment Thesis Track Record</h2>
            </div>
            <div className="grid grid-cols-4 gap-3">
              <div className="rounded-lg bg-[var(--background)] p-2.5 text-center">
                <p className="text-[9px] text-[var(--muted)]">Total</p>
                <p className="text-sm font-bold">{report.thesis.total}</p>
              </div>
              <div className="rounded-lg bg-[var(--background)] p-2.5 text-center">
                <p className="text-[9px] text-[var(--muted)]">Win Rate</p>
                <p className="text-sm font-bold text-[var(--gain)]">{report.thesis.winRate}%</p>
              </div>
              <div className="rounded-lg bg-[var(--background)] p-2.5 text-center">
                <p className="text-[9px] text-[var(--muted)]">Accuracy</p>
                <p className="text-sm font-bold">{report.thesis.avgAccuracy}/10</p>
              </div>
              <div className="rounded-lg bg-[var(--background)] p-2.5 text-center">
                <p className="text-[9px] text-[var(--muted)]">Discipline</p>
                <p className="text-sm font-bold">{report.thesis.avgDiscipline}/10</p>
              </div>
            </div>
          </div>

          {/* Section 4: Behavioral Analysis */}
          <div className="rounded-xl border border-[var(--card-border)] bg-[var(--card)] p-5 space-y-3">
            <div className="flex items-center gap-2">
              <Brain className="h-4 w-4 text-indigo-400" />
              <h2 className="text-sm font-bold">Behavioral Patterns</h2>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div className="space-y-2">
                <p className="text-[10px] font-semibold text-[var(--gain)]">Top 3 Strengths</p>
                {report.strengths.map((s, i) => (
                  <div key={i} className="flex items-start gap-2">
                    <CheckCircle2 className="h-3 w-3 text-[var(--gain)] shrink-0 mt-0.5" />
                    <p className="text-[10px] leading-relaxed">{s}</p>
                  </div>
                ))}
              </div>
              <div className="space-y-2">
                <p className="text-[10px] font-semibold text-[var(--loss)]">Top 3 Weaknesses</p>
                {report.weaknesses.map((w, i) => (
                  <div key={i} className="flex items-start gap-2">
                    <AlertTriangle className="h-3 w-3 text-[var(--loss)] shrink-0 mt-0.5" />
                    <p className="text-[10px] leading-relaxed">{w}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Section 5: Investor Summary */}
          <div className="rounded-xl border-2 border-indigo-500/30 bg-indigo-500/5 p-6 space-y-3">
            <div className="flex items-center gap-2">
              <User className="h-5 w-5 text-indigo-400" />
              <h2 className="text-sm font-bold">Who You Are as an Investor</h2>
            </div>
            <p className="text-xs leading-relaxed">{report.summary}</p>
          </div>
        </div>
      )}

      <p className="text-[10px] text-[var(--muted)] text-center pb-4">
        This report is generated from your app data. It is not financial advice.
        Share with a qualified advisor for personalized guidance.
      </p>
    </div>
  );
}


// ─── Report Builder (all from localStorage) ──────────────────────────────────

interface HoldingData { symbol: string; shares: number; avgCost: number; }
interface Report {
  riskProfile: string; startDate: string;
  holdings: HoldingData[]; totalUSD: number; totalDKK: number; totalReturnPct: number;
  thesis: { total: number; winRate: number; avgAccuracy: number; avgDiscipline: number; };
  strengths: string[]; weaknesses: string[];
  summary: string;
}

function buildReport(): Report {
  // Risk profile
  let riskProfile = 'Moderate';
  try { riskProfile = JSON.parse(localStorage.getItem('smartvest_profile') || '{}').riskProfile || 'Moderate'; } catch {}

  // Holdings
  let holdings: HoldingData[] = [];
  try {
    const orders = JSON.parse(localStorage.getItem('smartvest_orders') || '[]');
    const map: Record<string, { shares: number; totalCost: number }> = {};
    for (const o of orders) {
      if (o.type === 'buy') {
        if (!map[o.symbol]) map[o.symbol] = { shares: 0, totalCost: 0 };
        map[o.symbol].shares += o.shares;
        map[o.symbol].totalCost += o.shares * o.price;
      } else if (o.type === 'sell' && map[o.symbol]) {
        map[o.symbol].shares -= o.shares;
      }
    }
    holdings = Object.entries(map).filter(([,v]) => v.shares > 0)
      .map(([symbol, v]) => ({ symbol, shares: v.shares, avgCost: v.totalCost / v.shares }));
  } catch {}

  const totalUSD = holdings.reduce((s, h) => s + h.shares * h.avgCost, 0);
  const totalDKK = totalUSD * 6.85;

  // Thesis stats
  let thesisStats = { total: 0, winRate: 0, avgAccuracy: 0, avgDiscipline: 0 };
  try {
    const theses = JSON.parse(localStorage.getItem('smartvest_theses') || '[]');
    const closed = theses.filter((t: any) => t.status === 'closed');
    const wins = closed.filter((t: any) => t.actualOutcome === 'profit');
    thesisStats = {
      total: theses.length,
      winRate: closed.length > 0 ? Math.round((wins.length / closed.length) * 100) : 0,
      avgAccuracy: closed.length > 0 ? Math.round(closed.reduce((s: number, t: any) => s + (t.thesisScore || 5), 0) / closed.length * 10) / 10 : 0,
      avgDiscipline: closed.length > 0 ? Math.round(closed.reduce((s: number, t: any) => s + (t.disciplineScore || 5), 0) / closed.length * 10) / 10 : 0,
    };
  } catch {}

  // Behavioral strengths/weaknesses (derived from available data)
  const strengths = generateStrengths(riskProfile, holdings, thesisStats);
  const weaknesses = generateWeaknesses(riskProfile, holdings, thesisStats);
  const summary = generateSummary(riskProfile, holdings, thesisStats, strengths, weaknesses);

  return {
    riskProfile,
    startDate: new Date().toLocaleDateString('en-GB', { month: 'long', year: 'numeric' }),
    holdings,
    totalUSD,
    totalDKK,
    totalReturnPct: holdings.length > 0 ? 0 : 0, // Would need live prices for real calc
    thesis: thesisStats,
    strengths,
    weaknesses,
    summary,
  };
}

function generateStrengths(profile: string, holdings: HoldingData[], thesis: any): string[] {
  const strengths = [];

  if (holdings.length >= 5) {
    strengths.push('You maintain a diversified portfolio with multiple positions, reducing single-stock risk.');
  }
  if (thesis.total > 0) {
    strengths.push('You document your investment reasoning before buying — most beginners skip this critical step.');
  }
  if (thesis.avgDiscipline >= 6) {
    strengths.push('You show good discipline following your own rules for stop-losses and profit targets.');
  }
  if (holdings.length > 0 && holdings.length <= 15) {
    strengths.push('Your portfolio size is manageable — you can track each position without being overwhelmed.');
  }
  if (profile === 'Conservative' || profile === 'Moderate') {
    strengths.push('You chose a risk profile appropriate for a beginner and are sticking to it.');
  }

  // Defaults if we don't have enough data
  if (strengths.length < 3) {
    strengths.push('You are using a structured app to track investments rather than trading on impulse.');
    strengths.push('You are learning about markets systematically before committing large amounts of money.');
    strengths.push('You are aware of your risk tolerance, which most beginners ignore until it is too late.');
  }

  return strengths.slice(0, 3);
}

function generateWeaknesses(profile: string, holdings: HoldingData[], thesis: any): string[] {
  const weaknesses = [];

  if (holdings.length === 0) {
    weaknesses.push('You have not yet built a portfolio — analysis paralysis can cost years of compound growth.');
  }
  if (holdings.length > 0 && holdings.length < 3) {
    weaknesses.push('Your portfolio is very concentrated in few stocks, increasing risk if any single one drops.');
  }
  if (thesis.total === 0) {
    weaknesses.push('You have not written any investment theses — buying without documenting your reasoning makes it impossible to learn from mistakes.');
  }
  if (thesis.avgDiscipline > 0 && thesis.avgDiscipline < 5) {
    weaknesses.push('You tend not to follow your own exit rules. When you set a stop-loss, you need to honor it.');
  }
  if (thesis.winRate > 0 && thesis.winRate < 40) {
    weaknesses.push('Your thesis win rate is below 40% — spend more time on risk analysis before buying.');
  }

  // Defaults
  if (weaknesses.length < 3) {
    weaknesses.push('As a new investor, you lack experience with market downturns — your first 20% drop will test your resolve.');
    weaknesses.push('Without years of data, it is hard to know if your returns come from skill or luck. Keep tracking.');
    weaknesses.push('Beginners often check prices too frequently, leading to emotional decisions. Consider checking weekly not daily.');
  }

  return weaknesses.slice(0, 3);
}

function generateSummary(profile: string, holdings: HoldingData[], thesis: any, strengths: string[], weaknesses: string[]): string {
  const holdingCount = holdings.length;
  const totalValue = holdings.reduce((s, h) => s + h.shares * h.avgCost, 0);

  let summary = `You are a ${profile.toLowerCase()} investor `;

  if (holdingCount === 0) {
    summary += 'in the early learning phase. You have not yet committed capital but are building knowledge through the app. ';
    summary += 'This is actually a strength — most people invest before understanding what they are doing. ';
  } else {
    summary += `with ${holdingCount} active positions worth approximately $${Math.round(totalValue).toLocaleString()}. `;
  }

  if (thesis.total > 0) {
    summary += `You have written ${thesis.total} investment theses, showing a structured approach to decision-making. `;
    if (thesis.winRate >= 50) {
      summary += `Your ${thesis.winRate}% win rate indicates solid reasoning ability. `;
    } else if (thesis.winRate > 0) {
      summary += `Your ${thesis.winRate}% win rate has room for improvement — focus on identifying risks before buying. `;
    }
  }

  summary += `Your greatest strength is ${strengths[0].toLowerCase()} `;
  summary += `Your primary area for improvement is that ${weaknesses[0].toLowerCase()} `;

  summary += `Overall, you are developing as a thoughtful, risk-aware investor. `;
  summary += `The fact that you are tracking your behavior, scoring your theses, and comparing against benchmarks `;
  summary += `puts you ahead of most retail investors who trade purely on emotion. `;
  summary += `Continue building your track record — the longer your history, the more useful this report becomes `;
  summary += `for a financial advisor to give you genuinely personalized guidance.`;

  return summary;
}
